"""empty message

Revision ID: 009ea4efb6e3
Revises: 1bf63cf0ba49
Create Date: 2021-10-20 19:56:55.902994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009ea4efb6e3'
down_revision = '1bf63cf0ba49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('test', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
